### ISSUE TITLE
Game freezes

### ISSUE THREAD

**Issue by oschettler** [m2u-84/ludum-dare-44#1]
Hey the game already looks amazing. At one point however, it freezes:

![Screenshot from 2019-04-28 19 41 14](https://user-images.githubusercontent.com/124634/56868090-28d9b500-69ee-11e9-9dd7-b81cbf0c7b00.png)

The message is:

TypeError: path is null[Learn More] WalkingPerson.js:65:23
	planPath file:///home/olav/work/ludum-dare-44/src/game/WalkingPerson.js:65
	moveTo file:///home/olav/work/ludum-dare-44/src/game/WalkingPerson.js:56
	walkToCorpse file:///home/olav/work/ludum-dare-44/src/game/FacilityManager.js:128
	nextState file:///home/olav/work/ludum-dare-44/src/game/FacilityManager.js:46
	waitForCorpse file:///home/olav/work/ludum-dare-44/src/game/FacilityManager.js:103
	update file:///home/olav/work/ludum-dare-44/src/game/WalkingPerson.js:29
	update file:///home/olav/work/ludum-dare-44/src/game/FacilityManager.js:26
	update file:///home/olav/work/ludum-dare-44/src/stages/GameStage.js:124
	update file:///home/olav/work/ludum-dare-44/src/StageManager.js:186
	handleFrame file:///home/olav/work/ludum-dare-44/src/script.js:36

**Comment by m2u-84** [comment]
Thanks for bringing this to our attention. It had been fix before the game went live on LDjam.
